<script setup>
import '../../assets/ficha-libro.css'
import { ref } from 'vue'

const mostrarSpoiler = ref(false)
</script>

<template>
    <section class="libro">
        <div class="Introduccion">
            <h1>En llamas</h1>
            <p>Sinsajo es la tercera novela y el final de la Trilogía Los Juegos del Hambre, escrita por Suzanne Collins. Fue lanzado el 24 de agosto de 2010. </p>
            <p>El libro fue lanzado el 01 de septiembre 2009, y fue lanzado más tarde en Kindle y en formato de audiolibro. El libro tuvo una impresión inicial de 350.000 ejemplares. En Llamas, ha recibido principalmente críticas muy positivas. Los críticos elogiaron la forma en la que está escrito, el final y cómo Katniss se hizo más sofisticada.</p>
            <img src="../../Media/Libros/Portadas/llamasPortada.webp" alt="En llamas" class="imagen">
        </div>
        <div class="Informacion">
            <h2>Trama</h2>
            <hr>
            <div class="spoiler" :class="{ 'spoiler--revelado': mostrarSpoiler }">
                <div class="spoiler__contenido">
            <p>Katniss Everdeen y Peeta Mellark ambos sobrevivieron a los Juegos del Hambre. Regresaron a casa deseando y esperando un futuro lleno de paz. Pero el Capitolio está enojado. Quiere venganza.</p>
            <p>Cuando los rumores de una rebelión que comenzó llegan a oídos de Katniss, todo cambia. Ahora, Peeta y Katniss se ven obligados a visitar los distritos en la Gira de la Victoria, todo puede salir mal, si Katniss y Peeta no llevan a cabo su acto de locamente enamorados. Si no, tanto sus familias y distrito podrían estar en peligro de la ira del Presidente Snow.</p>
            <h3>Parte I</h3>
            <p>Katniss está de vuelta en el Distrito 12, con diecisiete años, vive en la Aldea de los Vencedores con su madre, Prim, y sus vecinos Peeta y Haymitch. Pronto, los dos tienen que irse de casa de nuevo para la Gira de la Victoria, donde los ganadores de los Juegos del Hambre viajan a cada distrito y hacen varias apariciones y discursos. Katniss esperaba que cuando regresara a casa todo sería igual, pero ahora su mejor amigo, Gale, está más lejos que nunca, ahora que trabaja en las minas del Distrito 12 doce horas al día, y con la Gira de la Victoria cerca, Katniss lo tiene más en su mente que nunca. Durante gran parte del día, Katniss se aburre con su nueva vida, porque ahora, lo tiene todo: dinero, un buen hogar, y alimento. Un día después de que Katniss regresara a casa de cazar, un visitante inesperado aparece, el Presidente Snow, presidente de Panem. Le explica a Katniss que durante los últimos Juegos del Hambre, cuando trató de suicidarse con Peeta con las bayas, encendió un posible levantamiento en los distritos. Snow y Katniss tienen una larga conversación sobre el hecho de que si no convence a los distritos de que ella tomó esa decisión porque estaba loca de amor, entonces él personalmente se aseguraría de que ella sufra.</p>
            <p>Katniss, ahora convencida de que ha comenzado un fuego que no puede controlar, hace su mejor esfuerzo para convencer a todos de que ella y Peeta están locamente enamorados. Cuando ella y Peeta, finalmente parten hacia la Gira de la Victoria, se ponen de acuerdo de tratar de ser de nuevo amigos cuando no estén haciendo el papel de enamorados. Cuando la gira llega a su primer destino, el Distrito 11, Katniss conoce a las familias de Thresh y Rue (dos tributos que fueron asesinados por Tributos Profesionales en los 74º Juegos del Hambre). Cuando llega el momento de comenzar el discurso, Katniss da gracias a la gente del Distrito 11 por su regalo durante los Juegos y está a punto de irse cuando uno de los hermanos de Rue le da una mirada a Katniss que la hace volverse rápidamente para hacer un último discurso. Katniss le dice a todos acerca de la historia de cómo Thresh le perdonó la vida, y cómo Rue se convirtió en una valiosa aliada durante los Juegos. Después de su discurso, un anciano silba la melodía de cuatro notas de Rue, y la multitud simultáneamente hace el gesto tradicional del Distrito 12 para mostrar su agradecimiento a Katniss. Inmediatamente después de que Katniss termina su discurso, se da cuenta que olvidó algo, por lo que vuelve a recuperarlo. Allí, ve a un Agente de la Paz dispararle al hombre que silbó en la cabeza.</p>
            <p>Luego, Katniss y Peeta confiesan lo que sucedió a Haymitch. Él le dice a Katniss que le explique a Peeta lo que está pasando, Katniss le cuenta todo sobre el presidente Snow, los levantamientos, y cómo todos ellos están en peligro si algo no cambia pronto. Peeta se enoja y le dice a Katniss y Haymitch que no le guarden secretos, y luego se va.</p>
            <p>El resto de la Gira de la Victoria fue una misma rutina (dando discursos, comer en cenas de lujo, montarse en el tren, y dormir). Por último, Katniss y los demás llegan al Capitolio. Esa noche, cuando ella y Peeta fueron entrevistados por Caesar, Peeta realiza una propuesta de matrimonio falsa a Katniss, la cual acepta. Caesar estaba fuera de sí, el público se puso histérico de la emoción, y las multitudes en los distritos estaban rebosantes de felicidad. El presidente Snow a continuación, hizo una aparición inesperada para felicitar a la pareja de recién comprometidos. Después, Katniss le hizo un gesto discreto al presidente Snow para preguntarle si ella fue lo suficientemente convincente pero él responde "no" con un movimiento casi imperceptible de la cabeza. Katniss ahora sabe que su vida está en peligro, pero a pesar de eso, se sintió un poco aliviada, y se comportó como si nada hubiera pasado.</p>
            <p>Esa noche, Katniss cena en la mansión del presidente Snow y celebró como nunca antes. Muchos ciudadanos del Capitolio bebieron algo que les hacía vomitar para poder comer más. Pronto llegó el momento de irse, Katniss y Peeta se encuentran en su camino de regreso al Distrito 12. Katniss sufre de terribles pesadillas toda la noche en el tren, por lo que Peeta duerme en su cama, la calma y le hace compañía. Finalmente, regresan al Distrito 12 y se realiza una gran fiesta para ellos. Mientras estaba en la casa del Alcalde Undersee, Katniss ve en la televisión del alcalde que hay un levantamiento en el Distrito 8. Katniss organiza una reunión secreta con Gale, en la que Gale confiesa su amor por ella, pero ella sólo le contesta: "Lo sé". Gale se enoja y se sintió decepcionado, pero antes de abandonar a Katniss, ella le dice que hubo una rebelión en el Distrito 8. Gale luego dice que podría haber una rebelión en el Distrito 12 también, y sale corriendo para difundir la noticia. Katniss luego va donde Peeta para preguntarle quería huir con ella y él le dice que sí, pero al mismo tiempo que están discutiendo sus planes, ven que Gale está siendo violentamente azotado en la plaza por un hombre desconocido.</p>
            <p>Katniss trata de detener al hombre, cuyo nombre es Romulus Thread, pero él le da un latigazo en la cara. Katniss es gravemente herida, pero Haymitch y Peeta la salvan. Con el tiempo, la gente del Distrito 12 (incluyendo a muchos que frecuentan El Quemador), convencen a Thread para que dejara de azotar a Gale. Tan pronto como él se va, todo el mundo ayuda a Katniss a llevar a Gale donde su madre. La madre de Katniss trata de calmar el dolor al darle medicina, cuando de repente Madge, la hija del alcalde, viene con un poco de Morflina para ayudar a calmar el dolor de Gale. Más tarde esa noche, Katniss elije a Gale, pero todavía se debate entre Peeta y Gale.</p>
            <p>Al día siguiente, hay cambios enormes en el Distrito, son construídos varios puestos de azote y una horca, así como también una serie de ametralladoras encaramados en los tejados de la plaza. Mientras caminaban por el Distrito, Haymitch, Katniss y Peeta ven estas horribles herramientas de tortura, y luego el Quemador es destruído por los Agentes de la paz. La última cosa, que Katniss se da cuenta al salir de la plaza, es que ella no reconoce ninguna de las caras de los Agentes de la paz.</p>
            <p>Katniss se da cuenta de que no puede soportar estar en casa, así que entra en el bosque y se dirige al lago. Ve lo que parecen ser dos Agentes de la paz, antes de dispararles, uno de ellos sostiene una galleta con un Sinsajo en él.</p>
            <h3>Parte II</h3>
            <p>Las dos Agentes de la paz en realidad eran dos jóvenes mujeres que habían huido del Distrito 8. Sus nombres eran Bonnie y Twill, le dieron la noticia a Katniss sobre el levantamiento en su distrito, el distrito que hace los uniformes lo que explica porque ambas lo usaban. Ambas le dijeron que se dirigían al Distrito 13, lo cual a Katniss le pareció increíble y al principio no les creía. Ellas creían que la gente vivía bajo tierra en el Distrito 13. Bonnie y Twill explicaron a Katniss que sabían que el Distrito 13 existía porque el Capitolio siempre reusaba el mismo vídeo del Distrito 13 siempre que aparecía el Distrito en televisión, ya que creía a ver visto el mismo pájaron en los vídeos. Esto lleva a preguntarse a Katniss si el Distrito 13 realmente existe.</p>
            <p>Ella les da a las mujeres alimento y les enseña a cazar. Cuando llega la noche, las mujeres se van y ella vuelve al pueblo. Sin embargo, se da cuenta de que la cerca del Distrito está electrificada y es incapaz de entrar al pueblo a través de donde siempre lo hace. Decidió que tenía que salir saltando encima de la valla y buscó el árbol adecuado. Se subió y debió saltar desde 7 metros en el aire. Cuando aterrizó le dolió el coxis y el talón. Regresó a su casa y le dijo a su madre y a Prim que se había deslizado sobre el hielo lo que le causó sus lesiones, pero había dos Agentes de la paz allí esperándola. Sorprendidos de verla, porque sabían que ella estaba en el bosque y creían que quedaría atrapada en el otro lado de la valla.</p>
            <p>Estaban esperando a que ella no apareciera para poder llevarse a su familia para interrogarla. Por suerte, Haymitch, Peeta y Prim fueron capaces de inventar una historia para encubrirla. Después de que los Agentes de la paz se van, la madre de Katniss examina su fractura en el pie, y Peeta se queda con ella toda la noche después de que ella le pidió que se quedara. Ella estaba en cama, mientras que Peeta le hacía compañía, ambos añadieron información al libro de plantas medicinales y comestibles de su madre, con imágenes que Peeta dibujó.</p>
            <p>Una vez que sanó, su Equipo de Preparación vino a ayudarla con su sesión fotográfica para la boda, junto con Cinna. Ella les escucha hablar de que no habían tenido camarones en el Capitolio durante semanas y se da cuenta de que otros distritos se están rebelando. Al día siguiente, le habla a Haymitch y él le dice que debido a que el Distrito 12 es tan pequeño, todo el mundo tendría que unirse a ellos para derrocar a los Agentes de la paz y el Capitolio. Ese mismo día, Prim llegó a casa y le dijo a todos que había un programa en la televisión obligatorio esa noche, ella cree que es el video de la sesión fotográfica de los vestidos de novia de Katniss.</p>
            <p>Prim estaba en lo cierto, pero también hay otro gran anuncio. El Presidente Snow aparece con una caja de madera, y recuerda a la audiencia de los Días Oscuros y cuando comenzó los Juegos del Hambre. También dice que cada 25 años, el aniversario de los Juegos del Hambre está marcada por un Vasallaje de los Veinticinco, una versión glorificada de los Juegos. Él habla del primer Vasallaje, cuando todos los distritos tuvieron que votar por los tributos que iban participar en los Juegos del Hambre. En el segundo Vasallaje, cada distrito se vio obligado a enviar el doble de tributos a los Juegos del Hambre. La caja de madera contenía la información para el tercer Vasallaje. Snow sacó un sobre y leyó que los tributos masculino y feminino serían cosechados de la urna de vencedores existentes. Ya que el Distrito 12 tiene sólo tres ganadores, Peeta, Haymitch, y Katniss, Katniss supo que debía regresar a los Juegos del Hambre.</p>
            <p>Salió corriendo de su casa y entró en un sótano de una casa vacía a gritar y a llorar. Luego, va hacía la casa de Haymitch, donde él le dice que ya Peeta ha venido a visitarlo, y le dijo que Peeta quiere volver a la arena para proteger a Katniss. Ella le dice a Haymitch que hagan lo que hagan, ella quiere que Peeta regrese a casa con vida. Ella y Haymitch se emborrachan y la tarde siguiente, ella vuelve a ir a la casa Haymitch, pero Peeta ha vaciado todo su licor y amenazó con delatarlos o delatar a cualquiera que les vendiera licor. Él les dice que entrenaran para el Vasallaje porque dos personas se volverian a casa vivos, comienzan a trabajar y también estudiar las imágenes de los vencedores anteriores y a conocer a su competencia.</p>
            <p>El día de la cosecha, Katniss ha decidido decirle adiós a Gale, y decirle lo mucho que significa para ella. La cosecha tiene sólo a Katniss como única opción para el tributo femenino, y el tributo masculino elegido es Haymitch, sin embargo, Peeta se hace voluntario para tomar su lugar. En lugar de poder decir adiós a sus familias, son llevados directamente al tren hacia el Capitolio.</p>
            <p>Una vez en el Capitolio, comen y averiguaron quienes eran los otros competidores de los otros distritos. Esa noche, después de que Katniss se despertó por una pesadilla, va a ver a Peeta. Los dos se abrazan y son interrumpidos por un camarero llevando leche caliente. Deciden ver más vídeos, y encuentran el vídeo donde ganó Haymitch, el segundo Vasallaje de los Veinticinco, que nunca habían visto. Katniss reconoce el nombre de Maysilee Donner, ya que fue amiga de su madre, y se da cuenta de que es la gemela de la madre de Madge, amiga de Katniss. También ve a su madre llorando y abrazando a Maysilee cuando es llamada en la cosecha. Katniss también ve a Haymitch cuando fue elegido en la cosecha. Nota que tiene una mirada poderosa, y que es algo guapo.</p>
            <p>Haymitch se alió con Maysilee y ambos atravesaron el bosque que rodeaba un extremo de la arena; ahí descubrió el Campo de Fuerza que rodea la arena para evitar que los tributos se escapen. Quería investigar más a fondo, pero Maysilee no quería, así que ambos tributos se separaron. Justo después de que rompieran la alianza, Maysilee fue asesinada por una bandada de pájaros que clavaron sus picos en su garganta y Haymitch se quedó con ella hasta que murió, sosteniendo su mano.</p>
            <p>Haymitch se convirtió en uno de los dos últimos tributos restantes, el otro era un Tributo Profesional, una chica. La chica persiguió a Haymitch hasta el borde de la arena donde se encontraba el campo de fuerza. Ambos tributos estaban heridos, pero Haymitch lo estaba más; la tributo intentó ganar los Juegos durando más tiempo que Haymitch. Sin embargo, Haymitch utilizó el campo de fuerza durante la lucha final, cuando su adversario tiró un hacha hacía él, él se agachó, el hacha cayó en el campo de fuerza, rebotó y regresó clavándose en la cabeza de la chica. Haymitch fue coronado vencedor de los 50º Juegos del Hambre. Sin embargo, el Presidente Snow, estaba furioso por el truco de Haymitch con el campo de fuerza, que Katniss describió más tarde por ser "casi tan malo como las bayas". Katniss se preguntó qué hizo el Capitolio para castigar a Haymitch.</p>
            <p>Una vez que llegaron, son apurados para prepararse para la ceremonia de apertura. Justo antes de la ceremonia, Finnick Odair del Distrito 4 va donde Katniss, pidiéndole que divulgue sus secretos, pero ella lo hace que se aleje. Después de la ceremonia, Johanna Mason del Distrito 7 pasa delante de Katniss totalmente desnuda. Katniss no entiende por qué todo el mundo está actuando de manera extraña hasta que Peeta explica que para el Capitolio, ella es "inocente" y que están tratando de meterse bajo su piel, esto molesta a Katniss.</p>
            <p>Ellos van al piso del Distrito 12 donde ven a la Avox, Lavinia, de los 74º Juegos del Hambre y también ven a un nuevo Avox, que resulta ser Darius del Distrito 12, que trató de detener a Thread de azotar a Gale. Él, como todos los Avoxes, se vio obligado a tener su lengua cortada. Ella es advertida por Haymitch que no debe decir nada porque significaría un castigo para Darius. Más tarde, Haymitch les dice que deben formar alianzas este año y hacer amigos. Durante el entrenamiento, Katniss se hace amiga de Wiress y Beetee del Distrito 3, que señalan el campo de fuerza que separa los Vigilantes de los tributos. Katniss muestra sus habilidades de tiro con arco y es buscado por muchos para forma alianza. En evaluaciones con los Vigilantes, tanto Peeta como Katniss no estaban seguros de qué hacer. Peeta entra primero, y después Katniss. Ella no sabe lo que hizo Peeta, pero se puede decir que los Vigilantes están enojados. Ve a Plutarch Heavensbee, el nuevo Jefe de los Vigilantes, y tiene una idea. Ata una soga a un maniquí y con el jugo de las bayas, escribe el nombre de "Seneca Crane", el Ex-Jefe de los Vigilantes en los primeros Juegos de Katniss, que permitió que tanto Katniss como Peeta vivieran. Él fue colgado por orden del Presidente Snow.</p>
            <p>Después, se entera de que Peeta hizo un dibujo de Rue muerta cubierta con flores en el suelo que no pudo ser borrado, y fue escondido por los Vigilantes. Haymitch no estaba feliz porque ahora se han convertido en enemigos. Los resultados son mostrados, y Katniss le pregunta a Cinna si alguien ha recibido un 0. Pero en cambio, ella y Peeta ambos reciben una puntuación perfecta de 12. Haymitch les explica que eso lo hicieron para asegurarse de que los otros tributos apunten hacía ellos. Peeta y Katniss permanecen juntos esa noche, en este momento Katniss aceptó la muerte, ya que sabe que va a ser la chispa para la rebelión. Esa noche, no tienen pesadillas. Al día siguiente, se pasan todo el día y la noche juntos, solos en el techo.</p>
            <p>El día de la entrevista, el equipo de preparación entra en la habitación de Katniss y la encuentran durmiendo con Peets. Peeta se va y mientras el equipo de preparación empieza a llorar, se van uno por uno hasta sólo queda Venia. A continuación, se despide de Katniss y Cinna llega con su vestuario, elegido por el presidente Snow, el vestido de novia elegido de la sesión de fotos. Katniss se da cuenta que es más pesado que antes, pero Cinna le explica que le hizo algunas modificaciones y le dice que no levante los brazos hasta que gire al final de la entrevista.</p>
            <p>El ambiente de la entrevista es diferente de la del año anterior. Los tributos hablan en contra del Capitolio, preguntando por qué el presidente Snow no detiene esto si él es grande y poderoso. El segundo último tributo en hablar es Katniss, que viene al escenario con el vestido, pidiendo disculpas a la gente por no dejarlos ver su matrimonio. Ella gira y levanta los brazos y el vestido de novia se quema para revelar un vestido diferente. Cuando se mira en un televisor, se da cuenta de que Cinna la ha convertido en un Sinsajo.</p>
            <p>Aunque Cesear sabe lo que el vestido representa, al final sólo dice que se parece al símbolo de Katniss. Luego sigue Peeta, el último tributo en hablar. Él le dice a la audiencia que él y Katniss ya están casados, y les dice que Katniss está embarazada. Esto lleva a la audiencia a la locura y la histeria. Mientras Peeta va de regreso hacía los otros tributos, sostiene la mano de Katniss en medio del caos, y ella a su vez agarra la mano (muñón de lo que queda) de Chaff que está junto a ella, y luego todos los tributos unen sus manos antes de que el Capitolio tuviera tiempo de apagar las cámaras, y Katniss sabe que esto, la unión de los tributos en el escenario, levantará la rebelión en los distritos aún más. Effie se vio obligada a irse sin decir adiós a Peeta y Katniss, y ellos se despiden de Haymitch. Él les dice que se mantengan con vida, y que recuerden siempre quién es el verdadero enemigo.</p>
            <p>Mientras Katniss se encuentra en la habitación con Cinna cuando entra en el tubo para salir a la arena, todo se congela y no puede moverse. Ella mira a Cinna que sólo mueve la cabeza confuso, cuando tres Agentes de la paz irrumpen en la habitación, lo arresta, lo golpean y lo arrastran fuera de la habitación. Katniss congelada por el horror, observa todo esto pero luego es transportada a la arena.</p>
            <p>El tubo la deja en una placa en medio de aguas azules, aquí se da cuenta de que "no hay lugar para una chica en llamas".</p>
            <h3>Parte III</h3>
            <p>Cuando sonó gong, Katniss se lanzó al agua y nadó hasta la orilla, notando que sentía muy ligera y rápida. Primera en llegar a la Cornucopia, se dirige a las armas, ya que sabe que los Profesionales harían lo mismo. Escoge un arco y flechas, y se da la vuelta cuando oye un ruido, a punto de matar. Es Finnick con su tridente levantado. Ella ve su brazalete de oro que pertenecía a Haymitch y se da cuenta que esta es su manera de decirle que forme una alianza. Finnick le grita que se agache, y le lanza el tridente al tributo del Distrito 5. Buscaron entre los otros artículos y notaron que sólo había armas, nada de comida. Mientras los Profesionales hacían su camino hacia la costa, Katniss intenta dispararles, pero no lo logra y sólo le dispara a Gloss en la pantorrilla. Luego, apunta hacia Brutus, pero se las arregla para detener la flecha con su cinturón. Se da cuenta de que Peeta todavía está en la placa de metal y va a tratar de recuperarlo, pero Finnick se ofrece a hacerlo. Katniss también ve que Mags salta al agua y nada como un perro hasta la orilla. Cuando Peeta y Finnick están en la playa, Mags le explica a Finnick (que aparentemente es la única persona que la entiende) que los cinturones de sus trajes son dispositivos de flotación.</p>
            <p>De la playa, corren hacía la jungla. Finnick lleva a Mags y Peeta está a la cabeza del grupo. Después de su primera parada, Katniss se sube a un arbol para conseguir una mirada y ve que hay muchos cuerpos en el agua y en la playa, pero no puede ver quiénes son.</p>
            <p>A medida que caminan, en busca de agua, se da cuenta de un cuadrado brillante que es un campo de fuerza rodeando la arena. Antes de que pueda detenerlo, Peeta camina hacía el campo y es repelido hacia atrás, golpeando a Mags y a Finnick. Peeta no respira. Presa del pánico, Katniss comienza a darle una bofetada, pero su corazón se ha detenido. Finnick se ofrece a ayudar, practicandole RCP. Ella no se da cuenta de lo que está haciendo en un primer momento y comienza a luchar, pero él la empuja y Peeta finalmente es resucitado. Peeta le pregunta a Katniss como reconoció el campo de fuerza. Ella no quería hacerles saber que podía detectarlo visualmente, debido a que los Vigilantes podrían tomar represalias, por lo que les dice que lo escuchó. Después, se dan cuenta que tienen que seguir adelante y después de un rato, Katniss trepa a un árbol y observa que la arena es en realidad un círculo perfecto. Ella les dice que hay una círculo en el centro y que no veía nada de agua, pero que tal vez algún arroyo dentro de la selva.</p>
            <p>Después de descansar, Katniss se ofrece a cazar. Se da cuenta de animales que no reconoce y dispara a lo que ella llama una rata de árbol. Se da cuenta de que su nariz está húmeda, lo que significa que debe haber agua cerca, pero no la puede localizar. Lleva comida de vuelta al campamento, donde Peeta tiene la idea de lanzar la comida al campo de fuerza para cocinarla. Más tarde, es anunciado los primeros caídos de los Juegos: el tributo del Distrito 5, asesinado por Finnick, el tributo del Distrito 6, Cecelia y Woof del Distrito 8, ambos tributos del Distrito 9, la tributo del Distrito 10, y Seeder del Distrito 11.</p>
            <p>Más tarde, cae un paracaídas plateado, Peeta lo abre y encuentra un tubo de metal pequeño, que nadie puede identificar. Sabiendo que Haymitch nunca envía nada a menos que sea para salvar vidas, Katniss se detiene a pensar. Frustrada, piensa en su familia y lo recuerda: es una espita, que puede ser insertada en un árbol como un grifo, para sacar la salvia. Estos árboles, sin embargo, contienen agua, que el grupo bebe más tarde. Luego, Finnick toma la primera guardia mientras los demás duermen. Katniss se despierta por el sonido de unas campanas, mientras que Peeta y Mags duermen. Finnick cuenta con 12 campanadas, y ve un rayo lejos. Después de una hora, el rayo se detiene y comienza la lluvia. Ella escucha los cañones indicando la muerte de otro tributo. Luego observa que hay niebla acercándose, y se da cuenta que es una niebla artificial creado por los Vigilantes. La bruma de la niebla causa ampollas en cuanto te toca. Cuando Peeta tropieza, también se da cuenta que ataca los nervios, ya que la mitad de su cara se paraliza y sus piernas dejan de funcionar. Finnick se compromete a llevar a Peeta, si Katniss puede llevar a Mags, lo cual ella acepta. Pero después de un rato, Katniss no puede llevar más Mags porque sus piernas se paralizan. Finnick le dice a Katniss que no puede llevar a los dos. Mags besa a Finnick y se va a la niebla, sufre unas convulsiones y muere. Los tres continúan su camino, lejos de la niebla. Después de no poder moverse más, debido al agotamiento, Katniss se da vuelta hacía la niebla y se da cuenta de que la niebla desaparece contra una pared invisible. Katniss encuentra la playa del comienzo de los Juegos, que al principio quema, pero se da cuenta de que el agua hace que el veneno de la niebla salga de su cuerpo. Poco a poco se sumerge en el agua y Peeta hace lo mismo. Finnick está muy herido para hacerlo por sí mismo, por lo que Peeta y Katniss lo ayudan. Después de recuperar su fuerza, Peeta se dispone a sacar agua de un árbol cercano. Katniss y Finnick estaban sentados y cuando Katniss escuchó varios monos reuniéndose. Ella trata de alertar a Peeta con calma, pero mientras Peeta se acercaba a ellos, los monos empezaron a atacar. Katniss se da cuenta de que son Mutos. Después de matar a varios, uno de ellos apunta hacia el pecho de Peeta, que está en esos momentos desarmado. Katniss intenta ayudarlo pero falla. De repente la Adicta a la Morflina del Distrito 6 aparece y ataca al mono, siendo mordida varias veces por los mutos. Los monos se van. Después, Peeta lleva a la chica a la playa y se da cuenta que los monos mordieron un órgano vital. Se quedan con ella hasta que muere.</p>
            <p>Más tarde, Katniss pide a Haymitch medicina para las costras de la niebla, y él se las da, junto con una barra de pan. Mientras comen, se escucha un grito y ven una gran ola a través y a pesar de que están lejos, el agua llega a su campamento. Se escucha un cañón y se dan cuenta de que sólo quedan 12 vencedores. El trío ve tres cuerpos caminando hacía ellos, y notan que uno de ellos es Johanna Mason. Finnick corre hacia ella y se abrazan. Mientras Katniss y Peeta piensan qué hacer, se dan cuenta que no dejar a Finnick después de todo lo que ha hecho, y van donde Johanna. Ella tenía a Beetee y a Wiress con ella. Beetee había recibido una herida en la espalda, mientras que Wiress giraba en círculos, y los tres estaban cubiertos de una sustancia roja. Johanna explica que cuando el rayo terminó y empezó a llover, ellos pensaron que era agua, pero resultó ser sangre. Mientras tanto, Wiress comenzó a girar en círculos de nuevo mientras decía "tic, tac, tic, tac". Johanna le grita a Wiress y la empuja al suelo, Katniss le dice que le un descanso a Wiress, lo cual Johanna responde golpeando a Katniss.</p>
            <p>Más tarde, durante la primera guardia, Johanna y Katniss hablan de Mags y la forma en que murió. Además, Katniss le pregunta qué estaba haciendo con Wiress y Beetee, Johanna le respondió que Haymitch le dijo que se los llevara a Katniss por una alianza. Más tarde esa noche, Katniss ve el relámpago, Wiress vuelve a decir "tic tac", y Katniss comienza a darse cuenta de que la arena tiene la forma y funciona como reloj. Wiress se alivia porque alguien la entiende, y Katniss explica rápidamente la situación para el equipo. También recordó que Plutarch Heavensbee le mostró su reloj, diciendo: "Ya casi es medianoche", mientras que una imagen de un sinsajo aparecía en la esfera del reloj.</p>
            <p>Ellos van a la Cornucopia para ver si están en lo cierto y descubren que si lo están. Beetee, empezó a sentirse un poco mejor, y le dice al grupo que Wiress no sólo es muy inteligente, pero que muy intuitiva. Mientras dibujan el mapa del reloj, Katniss se da cuenta de que Wiress ha dejado de cantar, y se da la vuelta con una flecha preparada y le dispara a Gloss, mientras que Johanna entierra su hacha en el pecho de Cashmere. Mientras trataban de perseguir a los tributos del Distrito 2, la Cornucopia comenzó a girar rápidamente. Beetee cae fuera de la isla, y Katniss va hacía el cuerpo de Wiress para recuperar un cable que Beetee quería desesperadamente.</p>
            <p>Cuando regresan a la selva, llegan a la conclusión de que las secciones de la selva podrían haber sido cambiadas y no lo sabrán hasta que salga la ola. Además, Katniss comienza a darse cuenta de que todo el mundo protege a Peeta y se pregunta si creen que él pueda ser el líder de la rebelión. En este punto, oye gritar a Prim y corre hacia ella, sólo para darse cuenta que los gritos vienen de un Charlajo. Finnick corre a buscar Katniss cuando escucha un grito también, y corre tras el. Katniss lo sigue a través de la selva y encuentra a otro charlajo gritando con la voz de Annie. Katniss trepa a un árbol para matar al charlajo pero Finnick tiene el corazón roto. Finnick le explica a Katniss que puede que no sea su Annie, pero que los charlajos imitan lo que escuchan, y se pregunta con horror cuándo los charlajos escucharon esos gritos. A medida que comienza a escuchar la voz de Gale en un charlajo, Finnick agarra el brazo de Katniss y la arrastra de nuevo a la selva donde se encuentran Peeta y Johanna. Molesta porque Peeta no le ayuda, se da cuenta que Peeta está gritando pero no escucha nada, se da cuenta de que tanto ella como Finnick están encerrados en esa parte de la selva por una pared invisible. Están atrapados en una sección del reloj, y los charlajos llegan con sus gritos de horror durante la siguiente hora hasta que la pared desaparezca. Peeta tranquiliza a Katniss diciéndole que Prim y los demás no fueron torturados. Como son los 8 finalistas, sus familias serán entrevistadas y no pueden hacerlo si sus familias están muertas. Finnick le pregunta a Beetee si es verdad, y él está de acuerdo con Peeta.</p>
            <p>Más tarde, Peeta intenta darle a Katniss un medallón de oro con fotos de Gale, Prim, y su madre como un recordatorio de todas las personas que dependen de ella. Él insiste en que ella debe sobrevivir, en lugar de él, porque si ella muere, él no tiene nada por qué vivir. Katniss lo besa con verdadero sentimiento, como cuando estaban en la cueva en los Juegos anteriores, y decide que aún debe tratar de seguir con su plan. Al día siguiente, Katniss le pide a Peeta que ambos dejen la alianza, pero él le dice que esperen un momento porque cree que Beetee tiene un plan. El plan consiste en atar el cable de Beetee alrededor del árbol del rayo (que es alcanzado por un rayo a las 12:00) y pasar el cable por la playa, haciendo que la playa sea un conductor de electricidad a cualquiera que esté en su paso. Katniss y Johanna son las encargadas de instalar el cable en la playa, ya que son las más rápidos, sin embargo, son atacados por Brutus y Enobaria. Justo antes del ataque, Katniss es golpeada por Johanna, a través de su visión borrosa, ve a Johanna encima de ella, apuñalandole el brazo. Johanna le dice que se quede quieta, y sale corriendo.</p>
            <p>Katniss oye a Finnick corriendo, pero se queda callada para no dar pista de su paradero, ya que ella cree que él y Johanna los han traicionado. Se esfuerza en caminar al árbol del rayo y ve a Beetee en el suelo con un cuchillo y más alambre. Ella ve que él estaba tratando de "cortar" el campo de fuerza que se encontraba arriba del árbol. Luego, se da cuenta de que más allá del campo de fuerza está el mundo real. En ese momento, escucha a Peeta llamándola por su nombre, y sólo porque se encontraba tan herida, hace lo único que puede, que es llamarlo también a él, alertando a todos los enemigos de su paradero para que Peeta pudiera tener la oportunidad de ganar.</p>
            <p>Se desploma después de escuchar los cañones, y recuerda las últimas palabras de Haymitch: "Recuerda quién es el verdadero enemigo", y se da cuenta de que se estaba refiriendo al Capitolio. Dándose cuenta de que Beetee estaba tratando de volar el campo de fuerza, envuelve el alambre alrededor de una flecha y dispara directamente a la falla del campo de fuerza en el momento exacto cuando el rayo cae sobre el árbol, volando la arena.</p>
            <p>Se queda ahí pensando en que el Capitolio no dejaría a nadie vivir después de esto, y que acababa de matar a Peeta a causa de esto. Ella ve a Plutarch Heavensbee acercándose en un aerodeslizador hacía ella, cierra los ojos y se desmaya. Más tarde, se despierta en una cama de hospital junto a Beetee. Busca a Peeta, creyendo que el Capitolio la ha capturado, planea matar a Peeta para salvarlo de ser torturado.</p>
            <p>Camina hacía una habitación y escucha hablar a Plutarch, Finnick y Haymitch sobre tratar de sacar a alguien del Distrito 4. Abre la puerta y Haymitch le dice que había un plan para salvarla justo en el minuto que el Vasallaje se anunció. Los vencedores del 3, 4, 6, 7, 8, y 11 tenían diversos grados de conocimiento sobre el mismo. Plutarch había sido durante varios años parte de un grupo que planeaba derrocar el Capitolio. Él se aseguró de que el cable fuera una de las armas, ya que se iba a utilizar para hacer explotar el campo de fuerza. Las hogazas de pan eran el código para el rescate. El aerodeslizador es del Distrito 13, que es a donde se dirigían en ese momento. Molesta, le pregunta por qué ella y Peeta no fueron informados. Haymitch explica que una vez que el campo de fuerza explotó, ella y Peeta serían los principales objetivos y era mejor si menos sabían del plan, en caso de que los capturaran. Ella les dice que Johanna trató de matarla, pero Finnick le explica que ella le quitó el dispositivo de seguimiento, y que todos los otros Vencedores se habían comprometido en dar sus vidas a ella y a la rebelión, ya que ella es el Sinsajo, el símbolo de la rebelión.</p>
            <p>Se da cuenta de que Haymitch nunca tuvo ningún plan de mantener a Peeta vivo. Él le dice que todo el mundo trataba de mantener a Peeta con vida porque sabía que si él moría, ella nunca haría una alianza con los demás. Ella le pregunta dónde está Peeta y Haymitch le dice que fue secuestrado, junto con Johanna y Enobaria, por el Capitolio. Sumida en horror y rabia, ataca a Haymitch, arañando su cara. Finnick y los demás la sujetan y la drogan para mantenerla en calma. Finnick le dice que el Capitolio por lo menos mantendrá a Peeta vivo para usarlo en contra de Katniss.</p>
            <p>Más tarde, Gale la visita. Le dice que después de los Juegos, el Capitolio envió bombas incendiarias a la veta. Le explicó que fue capaz de sacar a su familia a tiempo, pero que el 12 Distrito había sido destruido.</p>
            <img src="../../Media/Peliculas/enLlamas.jpg" alt="En llamas" class="imagen">
                    <button v-if="mostrarSpoiler" type="button" class="btn-spoiler btn-spoiler--ocultar" @click="mostrarSpoiler = false">Ocultar spoilers</button>
                </div>
                <button v-if="!mostrarSpoiler" type="button" class="spoiler__revelar" @click="mostrarSpoiler = true">Revelar spoilers</button>
            </div>

        </div>
        <div class="Personajes">
            <h2>Personajes</h2>
            <hr>
            <ul class="personajes-lista">
                <li class="personaje"><h3>Katniss Everdeen</h3><p>Vuelve a ser la narradora y personaje principal de la segunda entrega, enfrentando nuevos desafíos. Con el fin de probar su acción desesperada al final de los 74º Juegos del Hambre que fue provocada por amor y no rebelión contra el Capitolio, se ve obligada a convencer a la nación de su eterno amor por Peeta. Desafortunadamente, ella no pasa las expectativas del presidente Snow. Cuando se ve obligada a competir en los 75º Juegos del Hambre, Cinna la viste en su vestido de novia para la entrevista, pero debido a las alteraciones que le hizo, el vestido se quema y se convierte en un traje de sinsajo. Katniss batalla con su devoción por Peeta y Gale.</p></li>
                <li class="personaje"><h3>Peeta Mellark</h3><p>De diecisiete años, es el compañero tributo de Katniss. Se hace voluntario para tomar el puesto de Haymitch en el Vasallaje de los Veinticinco. Durante el Vasallaje, su corazón se detiene, pero Finnick lo revive con RCP. Es capturado por el Capitolio al final del libro.</p></li>
                <li class="personaje"><h3>Haymitch Abernathy</h3><p>Es el mentor de Katniss y Peeta. Es un alcohólico y usa la bebida para escapar de la tortura de los Juegos. Fue el único vencedor con vida del Distrito 12 antes de Katniss y Peeta y promete ayudar a Peeta a sobrevivir.</p></li>
                <li class="personaje"><h3>Effie Trinket</h3><p>Es la escolta de los tributos del Distrito 12. Es formal, correcta y extravagante. Ayuda a organizar los regalos de los patrocinadores junto con Haymitch y es arrestada al final de los 75º Juegos del Hambre.</p></li>
                <li class="personaje"><h3>Gale Hawthorne</h3><p>Es el mejor amigo de Katniss y su compañero de caza. Odia ferozmente al Capitolio y desea iniciar un levantamiento. Antes del Vasallaje, es azotado por Romulus Thread por cazar un pavo.</p></li>
                <li class="personaje"><h3>Presidente Coriolanus Snow</h3><p>Es el presidente de Panem. Su aliento huele a sangre y lleva una rosa blanca genéticamente modificada para tapar el olor.</p></li>
                <li class="personaje"><h3>Finnick Odair</h3><p>Es el tributo del Distrito 4 que ganó los 65º Juegos del Hambre con un tridente y una red. Demuestra ser valioso y digno de confianza, y es una persona clave en la rebelión.</p></li>
                <li class="personaje"><h3>Plutarch Heavensbee</h3><p>Fue el jefe de los Vigilantes en los 75º Juegos del Hambre y formaba parte de un grupo secreto cuyo objetivo era derrotar al Capitolio.</p></li>
                <li class="personaje"><h3>Mags</h3><p>Es la tributo del Distrito 4 y mentora de Finnick. Se queda en la niebla venenosa para que Finnick pueda llevar a Peeta a salvo.</p></li>
                <li class="personaje"><h3>Johanna Mason</h3><p>Es la tributo del Distrito 7. Ganó unos Juegos del Hambre anteriores y es capturada por el Capitolio junto con Peeta y Enobaria.</p></li>
                <li class="personaje"><h3>Beetee</h3><p>Es el tributo del Distrito 3, conocido como "Voltios". Es un inventor astuto y diseña el cable que permite volar el campo de fuerza de la arena.</p></li>
                <li class="personaje"><h3>Wiress</h3><p>Es la tributo del Distrito 3. Es muy inteligente y descubre que la arena del Vasallaje se comporta como un reloj. Es asesinada por Gloss.</p></li>
                <li class="personaje"><h3>Enobaria</h3><p>Es la tributo del Distrito 2. Es famosa por cortar la garganta de un tributo con los dientes y más tarde es capturada por el Capitolio.</p></li>
                <li class="personaje"><h3>Cinna</h3><p>Es el estilista de Katniss y transforma su vestido de boda en el símbolo de la resistencia, el sinsajo. Es golpeado y arrestado por los Agentes de la Paz.</p></li>
                <li class="personaje"><h3>Darius</h3><p>Es un Agente de la Paz del Distrito 12 que se convierte en un Avox por intentar detener a Romulus Thread.</p></li>
                <li class="personaje"><h3>Seneca Crane</h3><p>Fue el jefe de los Vigilantes en los primeros Juegos. Es asesinado por permitir que Katniss y Peeta ganaran.</p></li>
                <li class="personaje"><h3>Romulus Thread</h3><p>Es un despiadado Agente de la Paz y jefe de los agentes del Distrito 12. Azota a Gale como castigo por cazar y supervisa la quema del Quemador.</p></li>
            </ul>
</div>
    </section>
    <section class="pelicula">
        <div class="Pelicula">
            <h2>Adaptacion cinematografica</h2>
            <hr>
            <p>Lionsgate, productora encargada de adaptar los primeros tres libros a la pantalla grande, ha confirmado adaptar también una precuela de Los Juegos del Hambre, basada en una próxima novela de la escritora Suzanne Collins.</p>
            <p>“Como orgullosa productora de las películas de Los Juegos del Hambre, apenas podemos esperar a que se publique el próximo libro de Suzanne. Nos hemos estado comunicando con ella durante el proceso de escritura y esperamos seguir trabajando estrechamente con ella en la película". —Joe Drake, presidente del Grupo Lionsgate Motion Picture</p>
            <p>La pelicula, dirigida por Francis Lawrence, se estreno el 17 de noviembre de 2023. El guion fue escrito por Michael Lesslie y Michael Arndt. La película está protagonizada por Tom Blyth como Coriolanus Snow, Rachel Zegler como Lucy Gray Baird, Hunter Schafer como Tigris Snow, Jason Schwartzman como Lucretius "Lucky" Flickerman, Peter Dinklage como Casca Highbottom y Jason Mantzoukas como Dean Highbottom.</p>
            <img src="../../Media/Peliculas/llamas3.jpg" alt="En llamas" class="imagen">
        </div>
    </section>
</template>