<script setup>
import '../../assets/ficha-libro.css'
import { ref } from 'vue'

const mostrarSpoiler = ref(false)
</script>

<template>
    <section class="libro">
        <div class="Introduccion">
            <h1>Los Juegos del hambre</h1>
            <p>Los Juegos del Hambre es una novela distópica escrita por Suzanne Collins. Fue publicada originalmente el 14 de septiembre de 2008. El libro es el primero de la Tretalogía Los Juegos del Hambre, seguido por En llamas y después, Sinsajo y por ultimo una precuela llamada Balada de los pájaros cantores y serpientes.</p>
            <p>En la novela, los Juegos del Hambre es un evento televisivo anual en el que el despiadado Capitolio selecciona al azar un niño y una niña entre las edades de 12 a 18, de cada uno de los doce distritos, poniéndolos unos contra otros en un juego de supervivencia, donde se ven obligados a luchar entre sí hasta la muerte. El vencedor gana una nueva casa para ellos y sus familias en el Distrito, junto con comida, fama y riqueza.</p>
            <img src="../../Media/Libros/Portadas/juegosPortada.webp" alt="Los juegos del hambre" class="imagen">
        </div>
        <div class="Informacion">
            <h2>Sinopsis</h2>
            <hr>
            <p>"En una oscura versión del futuro próximo, doce chicos y doce chicas se ven obligados a participar en un reality show llamado Los Juegos del Hambre. Sólo hay una regla: matar o morir"</p>
            <p>"Cuando Katniss Everdeen, una joven de dieciséis años, se presenta voluntaria para ocupar el lugar de su hermana en los juegos, lo entiende como una condena a muerte. Sin embargo Katniss ya ha visto la muerte de cerca; y la supervivencia forma parte de su naturaleza."</p>
            <img src="../../Media/Peliculas/sinsajo.jpg" alt="Los juegos del hambre" class="imagen">
            <h2>Trama</h2>
            <hr>
            <div class="spoiler" :class="{ 'spoiler--revelado': mostrarSpoiler }">
                <div class="spoiler__contenido">
            <p>Cada año, durante 74 años, han tomado lugar Los Juegos del Hambre, obligando a 24 niños entre las edades de 12-18 (que son elegidos en una ceremonia llamada cosecha) a matarse entre sí, como castigo por la rebelión iniciada por el Distrito 13 contra el Capitolio. Este año no es diferente para Katniss Everdeen, hasta que su hermana menor, Prim, es llamada para participar. Ella toma el lugar de su hermana como tributo para salvarla de la muerte. Katniss hará cualquier cosa para sobrevivir, aunque tenga que ir en contra de sus propios estándares y morales. Pero cuando su compañero tributo revela su afecto por ella y otro comienza a actuar y le recuerda a su hermana, se hace más y más difícil encontrar una manera de sobrevivir sin matar a las personas más cercanas a ella.</p>
            <h3>Parte I</h3>
            <p>El Libro comienza con Gale Hawthorne y Katniss saliendo a escondidas hacia el bosque, que es el único lugar donde se sienten lo suficientemente seguros para discutir sobre El Capitolio y otros problemas. Siendo los cazadores, obtienen su botín del día y salen a venderlo al mercado negro del Distrito 12, El Quemador, a Sae la Grasienta y otros clientes. Una vez venden lo que cazaron, Gale y Katniss van a la casa del Alcalde Undersee a vender fresas. Cuando llaman a la puerta, Madge, la hija del alcalde, abre la puerta. Después de una pequeña discusión entre Gale y Madge, Katniss regresa a casa para estar lista para la cosecha. Debido a que el día de la cosecha no es un día feliz, Katniss trata de animar a Prim con comentarios sobre su vestido, un traje para otra cosecha que usó Katniss (el cual le queda un poco grande a Prim), y le dice "mete tu cola adentro, patito". Esto muestra el amor de Katniss hacía su hermana.</p>
            <p>En la cosecha, Prim es elegida como la tributo femenina del Distrito 12. Katniss, devastada y sorprendida, de inmediato se hace voluntaria para tomar el lugar de su hermana de doce años de edad. Hace algo que casi nunca se ve en el Distrito 12, ya que el último ganador del Distrito fue de casi 24 años atrás. Mientras el resto del Distrito se quedó en silencio, mirando sorprendidos, Katniss se convierte en el tributo femenino de su Distrito. Como un acto de respeto a un ser querido, todo el distrito coloca sus tres dedos de la mano izquierda en los labios y luego suben la mano como un saludo silencioso. Después de esto, el tributo que falta, Peeta Mellark, es elegido. Katniss recuerda la única interacción que tuvo con él hace tiempo atrás. Se angustia cuando recuerda que él le salvó la vida al tirarle una hogaza de pan.</p>
            <p>Katniss y Peeta son llevados en custodia, siendo vigilados para que no se escapen. A Katniss y a Peeta se le permiten tener visitar, Katniss tiene cinco. Cuando su madre y Prim llegan, le hace prometer a su madre que no abandone a Prim como hizo cuando su padre murió en la trágica explosión de la mina, ya que está segura de que no regresará a casa. Y le promete a Prim que va a esforzarse en ganar los Juegos. A continuación, el panadero, el padre de Peeta y con el que a menudo intercambian ardillas, es el siguiente en despedirse. Él le promete que va a cuidar de Prim y asegurarse de que coma. Su cuarto visitante, Madge, entra urgente y le ruega a Katniss que tome su insignia de sinsajo como su símbolo de distrito, una tradición en la que Katniss no había pensado hasta ese momento. Katniss titubeante se pone de acuerdo. Finalmente, Gale es envíado a la habitación. Su último encuentro no es muy largo pero Gale la deja con: "Recuerda que yo..." Katniss no escucha el resto porque Gale es sacado de la habitación.</p>
            <p>Después de la visitas de los familiares y amigos, son llevados al tren de los tributos que los llevará hasta el Capitolio. Cuando llegan al Capitolio son inmediatamente llevados al centro de preparación para arreglarse para la Ceremonia de Apertura, donde todos los tributos desfilan en el Centro de la Ciudad, en carrozas que reflejan las características de sus distritos. Cuando el Equipo de Preparación de Katniss, Venia, Flavius, y Octavia, terminan con las alteraciones básicas, Cinna, el estilista de Katniss, viene a mostrarle a Katniss su traje para la ceremonia. Él la viste con un traje entero negro y una capa. Katniss va hacia el establo para encontrar a Peeta con el mismo traje. Se montan en su carroza y Cinna y Portia, estilista de Peeta, encienden sus capas usando fuego sintético. Justo cuando la carroza está a punto de salir, Cinna le dice a Katniss y a Peeta que se tomen de las manos mientras recorren el camino a través de las calles deslumbrando a la gente del Capitolio.</p>
            <p>Las carrozas los llevan al Centro de Entrenamiento donde permanecerán hasta que comiencen los Juegos. Aquí entrenan en el gimnasio subterráneo hasta el día de la evaluación con los Vigilantes. Es ahí donde se muestran las mejores habilidades de cada tributo para obtener puntos de entrenamientos con los que conseguirán o no patrocinadores. Katniss es la última, ya que los tributos son llamados de acuerdo al número de su Distrito y género. Mientra entra, se da cuenta que los Vigilantes ya están borrachos y no le van a prestar atención. Su primer intento con el arco le sale mal ya que no está acostumbrada a la rigidez del arco. Sin embargo, dispara unas cuantas veces más para acostumbrarse al arma y termina disparándole a todos los objetivos. Unos cuantos de los Vigilantes se ven impresionados, pero la mayoría de ellos están pendiente de sus conversaciones. En un acto de desafío y rabia, dispara a una manzana que está en la boca de un cerdo asado de la mesa donde comen los Vigilantes, escandalizándolos en su mayoría. Luego esa noche cuando se muestran los puntajes, Katniss obtiene un 11 de 12, la máxima nota entre todos los tributos.</p>
            <p>Al día siguiente, son las entrevistas y Cinna viste a Katniss con un vestido de piedras preciosas con los colores de las llamas, representando a Katniss, como la chica En llamas. Durante su entrevista, Peeta confiesa su amor por Katniss a la nación de Panem, causando que surja una reacción inmensa de simpatía en la audiencia del Capitolio.</p>
            <h3>Parte II</h3>
            <p>Los Juegos comienzan con 11 de los 24 muriendo el primer día en el baño de sangre de la Cornucopia. Cuando comienzan los Juegos, Katniss considera conseguir un arco y flechas que ve cerca de la Cornucopia, pero decide no hacerlo cuando pierde su impulso después de una pequeña distracción de Peeta. Se aleja rápidamente, después de tratar de tomar todo lo que puede, entra en una pequeña pelea con un niño por una mochila, que termina cuando el niño es asesinado por Clove. Katniss casi muere cuando Clove le tira un cuchillo a ella, que ella bloquea con su mochila y se gana un buen cuchillo. En los próximos días, Katniss se aleja cada vez más lejos de la Cornucopia, durmiendo en la parte alta de los árboles, a pesar de que posteriormente es desacelerada por la falta de agua. Casi muere de sed, y llega hasta el punto de rogarle a Haymitch para obtener agua. Cuando no recibe respuesta, ve esto como una señal, o una manera de su mentor para decirle que no le envía agua porque hay una fuente cerca. Encuentra un pequeño estanque para beber, tumbándose ahí mientras pensaba en camuflar su mochila de color naranja brillante para que no llamara demasiado la atención.</p>
            <p>A la mañana siguiente se despierta ante un muro de fuego creado por los Vigilantes, incluyendo bolas de fuego que son arrojados a ella. Sobrevive a esto, pero sufre quemaduras leves en sus manos y una quemadura grave en la pantorrilla. Va a dormir y es despertada por el sonido de pasos. Katniss es perseguida por el grupo de los Profesionales Glimmer, Marvel, Cato,Clove, la chica del Distrito 4 y Peeta, y se escapa subiendo a un árbol. Cato intenta subir después de Katniss, pero cae al suelo, porque es demasiado pesado para las ramas. Todas las Profesionales son demasiado pesados ​​para subir tras ella y quedan a esperar a que baje. Durante este tiempo, Haymitch le envía un paracaídas con medicina para su pierna. Luego, Rue, aparece en un árbol cercano y apunta al nido de Rastrevíspulas por encima de Katniss. Katniss corta la rama que sostiene el nido con el cuchillo que recibió de Clove y las rastrevíspulas comienzan a atacar a los Profesionales, matando a Glimmer y a la chica de Distrito 4. Viendo esto como una oportunidad, toma el arco y las flechas de Glimmer, que obtuvo en la Cornucopia, pero antes es vista por Peeta que la deja escapar, por lo tanto se mete en problemas con Cato. Los otros Profesionales fueron picados por las rastrevíspulas al igual que Katniss, que pasa días en recuperarse.</p>
            <p>Cuando Katniss se despierta de las alucinaciones causadas por el veneno de las rastrevíspulas, propone una alianza con Rue, que le recuerda a Prim, tanto en tamaño como en comportamiento. Las dos se unen por varias cosas, sintiéndose cómodas entre ellas. Katniss y Rue luego planean destruir el los suministros y comida de los Profesionales. Rue distraerá a los Profesionales prendiendo 1 de 2 fogatas que ella y Katniss prepararon que Katniss vigilaría el campamento de los Profesionales. Se da cuenta de que los alimentos están protegidos por minas terrestres, que eran las minas que estaban en los círculos plateados al comienzo de los Juegos, las cuales fueron reactivadas por el tributo del Distrito 3. Ella observa cómo Foxface corre hacía el área, esquivando las minas y toma algo del suministro. Más tarde dispara a un saco por encima de las minas para hacer caer las manzanas que estaban dentro al suelo, lo que activó todas las minas. Casi todo es destruído y el oído de Katniss queda dañado, dejándola un poco "cegada".</p>
            <p>Katniss va al bosque, tratando de escuchar la melodía de Rue. Su melodía de cuatro notas suena por el bosque gracias a los sinsajos, pero de repente grita por Katniss. Sabiendo que se trata de problemas y, posiblemente, una trampa, corre entre los árboles para encontrar a Rue enredada en una red, con un brazo afuera señalando hacía Katniss antes de que una lanza es tirada hacía su estómago por el tributo del Distrito 1, cuyo nombre es luego revelado como Marvel. Katniss mata al chico de inmediato, se sienta junto a Rue, y canta la Canción del Valle. Ella muere después de que Katniss termina la canción. Después de ver a Rue muerta y enojada por que el Capitolio disfruta ver niños inocentes morir, Katniss recoge flores y decora el cadáver de Rue con ellas, ocultando la herida y tejiéndolas en su pelo. Después de esto hace el gesto de despedida del Distrito 12. Katniss piensa que los Vigilantes no permitirán transmitir mucho de esta escena ya que podría parecer un acto de rebelión desafiando al Capitolio. A continuación, toma la mochila de Rue y la del chico muerto, a sabiendas de que Rue hubiera querido que las tuviera. A medida que se aleja de Rue y el aerodeslizador recoge su cuerpo, un paracaídas cae desde el cielo para ella, conteniendo un pan en forma de medialuna salpicado de semillas, un regalo del Distrito 11, al parecer, se piensa que el regalo pudo haber sido destinado para Rue pero después de su muerte, el Distrito 11 decidió dárselo a Katniss ya quera aliada de Rue. Este regalo es muy significativo, y es el primer regalo que se conoce que ha sido regalado a un tributo de un distrito al que no pertenece. Después Claudius Templesmith anuncia que dos tributos podían ganar si eran del mismo distrito. Momentáneamente olvidando el daño potencial que le podría causar, Katniss grita el nombre de Peeta.</p>
            <h3>Parte III</h3>
            <p>La conclusión de Los Juegos del Hambre. Esta parte se centra principalmente en el final de los 74.os Juegos del Hambre y las consecuencias que conduce a los eventos en En llamas. Después de que se anunció que dos tributos de un mismo distrito podían ganar, Katniss encuentra a Peeta camuflado y se horroriza por la condición en la que se encuentra. Debido a haber salvado a Katniss, Cato le hace un corte en la pierna de Peeta. Katniss intenta curar a Peeta, pero se escandaliza cuando desarrolla septicemia. Claudis Templesmith luego anuncia que harán un Banquete, pero no cualquier otro banquete. A cada Distrito se le dará algo que necesitan para ganar... para el Distrito 12 algo para curar la pierna de Peeta. Bajo la promesa de que Katniss no iría al Banquete, Peeta es rápidamente engañado por Katniss que le da jarabe para el sueño enviado por Haymitch que lo haría dormir por un día, dándole a Katniss más del tiempo necesario para ir al banquete y recoger la medicina para Peeta. La Comadreja es la primera en tomar su mochila, corre tan rápido que Katniss pierde su impulso. Katniss corre para tomar la suya, una mochila lo bastante pequeña para entrar en su muñeca, con la etiqueta del 12. Mientras corre fuera del banquete, sosteniéndo la medicina que salvará a Peeta, Clove le lanza un cuchillo hacia Katniss que ella bloquea con su arco. Sin embargo, el segundo cuchillo le abre una herida por encima del ojo. Luego Clove se lanza sobre Katniss y le habla sobre la muerte de Rue y de cómo la va a matar de manera lenta y sádica. Justo cuando Clove está a punto de cortar a Katniss, Thresh, el tributo restante del Distrito 11, tira a Clove lejos y exige a Clove que le diga si mato a Rue. Clove lo niega a pesar de que había estado hablando de eso momentos antes, pero Thresh no cree éso y le rompe el cráneo con una roca, el cañón suena significando su muerte. Mientras Thresh se da la vuelta hacía Katniss, ella le pide que la mate rápido, pero Thresh le perdona la vida por haber sido aliada de Rue y de cuidarla mientras moría. Cato luego corre al cuerpo de Clove, así que Thresh deja a Katniss correr mientras él toma su mochila y la de Cato, de la mesa. Katniss corre hacía la cueva, inyecta la medicina a Peeta y se desmaya.</p>
            <p>Las cosas pasan después con ellos, ya sea quedándose en la cueva, descansando y recuperándose, o cazando y recolectando. El cañón de Thresh significando su muerte suena mientras Peeta y Katniss estaban atrapados en la cueva debido al mal tiempo. La Comadreja muere, después de que se roba y come unas bayas jaulas de noche que Peeta recogió, sin saber que eran mortales.</p>
            <p>En el último día de los Juegos, el río que pasa cerca de su cueva, se seca. Ellos ven esto como una señal de que los Vigilantes quieren reunir a los tres tributos restantes al lago cerca de la Cornucopia. Ahí es donde encuentran a un frenético Cato huyendo de unas enormes mutaciones del Capitolio, lobos con características humanas que se asemejan a la de los tributos muertos. En el espectáculo final en la parte superior de la Cornucopia estaba Cato tratando de usar a Peeta para detener a Katniss de matarlo. A la final falla ya que Katniss le dispara en la mano y cae fuera de la Cornucopia hacía donde están las mutaciones. Él no muere es simplemente torturado por las mutaciones debido a su armadura, que consiguió en el Banquete. Cato es gravemente herido por los mutos y a la final es matado por Katniss con una flecha en la cabeza. Su cañón suena, Katniss y Peeta se preguntaban por qué no eran anunciados vencedores. Claudius Templesmith luego anuncia que sólo puede haber un vencedor, revocando la regla anterior. Como una manera para desafiar a los Vigilantes, Katniss piensa en la idea de suicidarse con Peeta usando las bayas Jaulas de Noche, con la esperanza de que el Capitolio preferiría tener 2 vencedores que ninguno. Peeta acepta, justo cuando van a comer las bayas, son precipitadamente declarados vencedores. Sin embargo, el Capitolio se enoja con Katniss por "burlar" a los Vigilantes y por lo tanto desafiar al Capitolio. Cuando Haymitch dice esto a Katniss, ella lo ve como su trabajo revertirlo y salvar a las personas que quiere así que actúa su papel de loca de amor lo mejor que puede con el fin de convencerlos de que ella lo hizo por su futuro con Peeta. Al volver a casa, Peeta y Katniss empiezan a distanciarse, cuando ella le dice que sabía cuando Haymitch le iba a enviar regalos de patrocinio y sobrevivió la mayoría de los Juegos de esa manera. Los pensamientos de Katniss están en crisis, están en conflicto por sus sentimientos por Peeta y es incapaz de discernir si lo que sentía era real o no. Peeta ofrece su mano a Katniss, transmitiendo su dolor diciendo: "¿Una vez más? ¿Para el público?" Ella lo obliga, y el libro termina con su miedo de soltar al chico que poco a poco se aleja más de ella.</p>
            <img src="../../Media/Peliculas/juegos2.jpg" alt="Los juegos del hambre" class="imagen">
                    <button v-if="mostrarSpoiler" type="button" class="btn-spoiler btn-spoiler--ocultar" @click="mostrarSpoiler = false">Ocultar spoilers</button>
                </div>
                <button v-if="!mostrarSpoiler" type="button" class="spoiler__revelar" @click="mostrarSpoiler = true">Revelar spoilers</button>
            </div>

        </div>
        <div class="Personajes">
            <h2>Personajes</h2>
            <hr>
            <ul class="personajes-lista">
                <li class="personaje"><h3>Katniss Everdeen</h3><p>Protagonista de la historia, una adolescente sarcástica, decidida y de voluntad fuerte. Tiene dieciséis años al comienzo de la historia. Katniss vive en el Distrito 12, el distrito de la minería de carbón y uno de los distritos más pobres, vive en la parte apodada La Veta. Katniss a menudo caza fuera de las vallas del Distrito con el fin de alimentar a su familia. Su padre era un minero que murió en un accidente de la mina. Cuando Primrose, mayormente conocida como "Prim", hermana de Katniss, es escogida en la cosecha para Los Juegos del Hambre, pero Katniss se hace voluntaria para ocupar su lugar. Su caza y sus habilidades con el arco son clave para ella en Los Juegos del Hambre. Tiene el pelo negro y lacio, ojos grises claros, piel olivácea y por lo general lleva el pelo recogido en una trenza. Es apodada como Catnip por su mejor amigo, Gale, cuando se reúnan por primera vez en el bosque.</p></li>
                <li class="personaje"><h3>Peeta Mellark</h3><p>El Tributo masculino del Distrito 12, Peeta es hijo de un panadero. Ha estado enamorado de Katniss desde los cinco años, y una vez la salvó de morir de hambre. Peeta se caracteriza por una personalidad simpática, estrategia, y ser desinteresado. Tiene el pelo rubio y ojos azules, no como la gente de la Veta, la parte pobre del Distrito 12, donde vive Katniss, que tienen el pelo negro.</p></li>
                <li class="personaje"><h3>Gale Hawthorne</h3><p>El mejor amigo de Katniss, ella y Gale se conocieron cuando ella tenía sólo doce años y él tenía catorce años después de que sus padres murieron en la misma explosión minera. Gale caza con Katniss en el bosque, casi todos los días, pero en En llamas, sólo caza con ella los domingos. Katniss asumió erróneamente que su relación no era romántica.</p></li>
                <li class="personaje"><h3>Sra. Everdeen</h3><p>Es la madre de Katniss. Pasó por una gran depresión a causa de la muerte de su marido en el accidente minero. Abandonó a sus hijas encerrándose en su dormitorio para mirar las paredes, no comía durante días, ignorando su hambre y la de su familia. Como resultado de su negligencia, Katniss fue dejada con la difícil tarea de apoyar a su familia y encontrar maneras de buscar y cazar alimento, al final incluso el comercio era también necesario. Tiene el pelo rubio y ojos azules con piel de color claro, características comunes de la parte comerciante del Distrito 12, de donde es originalmente.</p></li>
                <li class="personaje"><h3>Cinna</h3><p>Estilista de Katniss, que más tarde se convierte en su amigo. Cinna es inteligente y solidario. Vive en el Capitolio. Hace trajes y vestidos impresionantes para Katniss, incluyendo el traje para el desfile de los tributos, el vestido para la entrevista, y el vestido amarillo brillante para su regreso a casa.</p></li>
                <li class="personaje"><h3>Portia</h3><p>Es la estilista de Peeta y trabaja junto a Cinna para diseñar los trajes de Peeta y Katniss. Vive en el Capitolio.</p></li>
                <li class="personaje"><h3>Rue</h3><p>La tributo del Distrito 11. Pequeña como un ave, está muy subestimada en los Juegos, pero su conocimiento de los árboles y cómo ocultarse la mantiene con vida más de lo esperado. Katniss piensa que se parece un poco a Prim. Advierte a Katniss sobre el nido de Rastrevíspulas, mutaciones creadas por el Capitolio para destruir la rebelión. Por desgracia, Rue fue asesinada por el tributo del Distrito 1, Marvel, que arrojó una lanza en su estómago. Katniss le cantó a Rue para que durmiera, luego murió. Después de que Rue cerró los ojos y sonara el cañón, Katniss reunió flores y cubrió a Rue con ellas, mostrando a los Vigilantes que ella era "más que una pieza en los Juegos". Katniss tenía una conexión especial con Rue, porque le recordaba a su querida hermana Prim.</p></li>
                <li class="personaje"><h3>Cato</h3><p>El tributo del Distrito 2. Descrito como una "máquina de matar implacable", es extremadamente fuerte y musculoso, era la opción más probable para ganar. También es descrito como apuesto y rubio y es considerado el Segundo más fuerte de los tributos. Él, Katniss y Peeta fueron los últimos tres tributos en enfrentar a los lobos mutados que tenían características de los tributos fallecidos. Cato fue debilitado por los mutos. Katniss y Peeta se escondieron arriba de la Cornucopia en la última noche en la arena esperando que sonara el cañón señalando la muerte de Cato, pero no sonaba. A la final, Cato surgió hecho pedazos. Después de horas de lamentos y gemidos, Katniss decidió poner fin a su miseria, disparando una flecha en su cráneo.</p></li>
                <li class="personaje"><h3>Clove</h3><p>La tributo del Distrito 2. Era muy experta en lanzar cuchillos, y fue quien mató al tributo del Distrito 9, que el fue el primer tributo en morir en los Juegos. Fue la quinta última persona en morir y fue al "banquete" en la Cornucopia (donde fue asesinada) con Cato haciéndole guardia. Clove parecía tener una conexión con Cato. Después de admitir tener cierta participación en la muerte de Rue, Thresh fractura su cráneo con una roca. Muere en los brazos de Cato, mientras Katniss huye por su vida.</p></li>
                <li class="personaje"><h3>Comadreja</h3><p>Conocida por ningún otro nombre, esta pelirroja del Distrito 5 es astuta y difícil de alcanzar. A pesar de que no tiene fuerza o en armas, su intelecto superior fue una herramienta vital en los Juegos. Es descrita por ser astuta y buena robando. Foxface ideó una forma para robar suministros de los Profesionales. Murió por accidente por comer unas bayas jaulas de noche, que robó de la comida de Peeta y Katniss. Quedó en cuarto lugar en los Juegos.</p></li>
                <li class="personaje"><h3>Thresh</h3><p>El tributo del Distrito 11. Desapareció durante la primera parte de los Juego. Esto lo hizo aún más peligroso porque estaba escondido en un campo de trigo con un lugar para dormir y alimento. Perdonó la vida de Katniss, porque era amiga de Rue. Se supone que fue asesinado por Cato, pero esto es desconocido.</p></li>
                <li class="personaje"><h3>Glimmer</h3><p>La tributos del Distrito 1, era muy hermosa, sexy, con el pelo largo, rubio y ojos color verde esmeralda. Murió en el ataque de Katniss con las Rastrevíspulas. Su ADN fue tomado para crear una mutación de lobo y no se sabe si su mutación sobrevivió durante la lucha con Cato, Peeta y Katniss.</p></li>
                <li class="personaje"><h3>Marvel</h3><p>El Tributo del Distrito 1, era parte de los Tributos Profesionales. Fue asesinado por Katniss, después de haber matado a Rue al tirarle una lanza en el estómago.</p></li>
                <li class="personaje"><h3>Haymitch</h3><p>Es el mentor de Katniss y Peeta. Haymitch es el único sobreviviente de los Juegos del Distrito 12. Peligroso y astuto, Haymitch por lo general está ebrio, con un vaso en una mano y un cuchillo en la otra. Dormía con un cuchillo en la mano. Prometió que estaría lo suficientemente sobrio para entrenar a Katniss y Peeta para los Juegos. Él envía regalos de los patrocinadores a Katniss a lo largo del libro para ayudarla a sobrevivir. Ganó el segundo Vasallaje de los Veinticinco, donde se requería el doble de los tributos.</p></li>
                <li class="personaje"><h3>Effie Trinket</h3><p>Es la escolta de los tributos del Distrito 12, Katniss y Peeta. Es muy formal y correcta, y posee claro acento del Capitolio. Los modales son muy importantes para ella, así como mantener un estricto horario. Se viste raro ya que es una residente del Capitolio. Ayuda a organizar los regalos de los patrocinadores junto a Haymitch para enviarle a Katniss durante los Juegos. Ella también eligió los tributos durante la cosecha para los 74.os Juegos del Hambre. Trató de ayudar a Peeta y Katniss con sus modales y etiqueta pero fue aterrorizada por la falta deliberada de modales en Katniss, rápidamente aumentó su frustración y se rindió. Se pone feliz y aliviada cuando Katniss y Peeta ganan los Juegos.</p></li>
                <li class="personaje"><h3>Primrose "Prim" Everdeen</h3><p>La hermana menor de Katniss Everdeen. En el primer libro de la serie, tiene sólo doce años, la suerte no estuvo de su lado, porque fue elegida para los Juegos. Tiene una cabra llamada Lady y un gato llamado Buttercup. Lady provee productos lácteos para la familia Everdeen. A diferencia de su hermana mayor, Prim tiene un corazón lleno de compasión y una afinidad para la curación, como el de su madre. Prim había sido elegida originalmente como tributo, hasta que Katniss se ofreció para tomar su lugar. Ella usualmente ayuda a su mamá con personas enfermas.</p></li>
                <li class="personaje"><h3>Flavius</h3><p>Miembro del equipo de preparación de Katniss. Usa lápiz labial de color púrpura. Flavius está a cargo de los peinados.</p></li>
                <li class="personaje"><h3>Venia</h3><p>Miembro del equipo de preparación de Katniss. Tiene el pelo color turquesa y tatuajes dorados por encima de las cejas.</p></li>
                <li class="personaje"><h3>Octavia</h3><p>Miembro del equipo de preparación de Katniss. Tiene la piel verde guisante.</p></li>
            </ul>

        </div>
    </section>
    <section class="pelicula">
        <div class="Pelicula">
            <h2>Adaptacion cinematografica</h2>
            <hr>
            <p>Lionsgate Entertainment adquirió los derechos de distribución en todo el mundo para la adaptación cinematográfica de Los Juegos del Hambre, es producida por la compañía de producción Color Force de Nina Jacobson. Suzanne Collins adaptó la novela para el cine, con el guionista Billy Ray, quién lo revisó. Gary Ross dirigió la película. Jennifer Lawrence interpretó el papel de Katniss Everdeen mientras que Josh Hutcherson y Liam Hemsworth interpretaron a Peeta Mellark y Gale Hawthorne, respectivamente. La película fue estrenada el 23 de marzo de 2012.</p>
            <img src="../../Media/Libros/Logos/juegosLogo.png" alt="Los juegos del hambre" class="imagen">
        </div>
    </section>
</template>