<script>
import '../assets/balada.css'
</script>

<template>
    <section class="libro">
        <div class="Introduccion">
            <h1>Sinsajo</h1>
            <p>Balada de pájaros cantores y serpientes es un libro precuela de la Trilogía escrita por Suzanne Collins. Su fecha de publicación fue el día 19 de mayo de 2020.</p>
            <p>El libro fue anunciado el 16 de junio de 2019 en la New York Comic Con por Scholastic Press. La autora anunció en un comunicado que volvería a los años posteriores, a los llamados Días Oscuros, la rebelión fallida en Panem. La portavoz de su editorial, Tracy van Straaten, declinó hacer comentarios sobre el contenido del nuevo libro o sobre personajes destacados más allá de lo descrito en el primer anuncio oficial.</p>
            <img src="../Media/balada.jpg" alt="Balada de pajaros cantores y serpientes" class="imagen">
        </div>
        <div class="Informacion">
            <h2>Trama</h2>
            <hr>
            <h3>parte I</h3>
            <p>El libro inicia con Katniss tomando su papel como rebelde en el Distrito 13. Sólo tres vencedores fueron salvados de la arena: Beetee (un hombre viejo del Distrito 3, conocido como Voltios), Finnick (el apuesto vencedor del Distrito 4 y el primer aliado de Katniss) y Katniss. Peeta no se halla entre los rescatados, en vez de ello está desaparecido, junto con otros vencedores como Enobaria (la tributo femenino del Distrito 2), Johanna (la tributo del Distrito 7) y Annie (que no estuvo en el Vasallaje de los Veinticinco pero fue arrestada cuando la arena estalló). Katniss es todavía asustada por Snow y teme por la vida de Peeta.</p>
            <p>El libro comienza en el Distrito 12, el cuál ha sido reducido a cenizas. Katniss por su parte ha insistido en ir sola a ver las ruinas del distrito. Nos encontramos con los sucesos ocurridos después de que la arena explotara. Mientras ella esta ahí, toma de vuelta a Buttercup (el gato de Prim), la vieja chaqueta de cazar de su padre, una foto de la boda de su madre y un libro de plantas. Antes de irse, se da cuenta que Snow le dejó una rosa blanca en su habitación, símbolo de su inminente venganza.</p>
            <p>Un aerodeslizador la lleva al Distrito 13 donde los sobrevivientes del Distrito 12 residen ahora. Una vez de regreso, ve una entrevista entre Caesar y Peeta. Katniss se encuentra aliviada al ver que Peeta luce ileso, incluso sano, pero durante la entrevista, Peeta llama a un cese de fuego lo que trae como consecuencia que sea acusado por muchos de los rebeldes como un traidor. En cambio, para Katniss, la entrevista y la reacción que provocó entre los rebeldes se convierte en el firme estímulo que concreta su decisión de transformarse en el Sinsajo, con la condición de que al final de la guerra se le otorgue inmunidad a Peeta y los otros tributos. Unido a esto, Katniss peticiona también por derechos de caza para ella y para Gale, el derecho de mantener Buttercup para Prim y permiso para, llegado el momento, matar a Snow.</p>
            <p>La presidenta Alma Coin, la líder del Distrito 13, acepta estas condiciones y Katniss se convierte oficialmente en el Sinsajo. Katniss se embarca entonces a protagonizar comerciales para los rebeldes llamados propos. Para su primera propo, ella y su equipo (que incluye a su viejo amigo Gale) son enviados al Distrito 8, donde quedan atrapados momentáneamente en un bombardeo y presencian la destrucción de un hospital. La situación inspira a Katniss a llamar por justicia, y una vez difundida, el efecto de la propo no se hace esperar. Luego, más adelante, durante la transmisión de una entrevista con Peeta en el Capitolio, Beetee es capaz de ganar control de la difusión y airear la propo por un corto tiempo antes de que comience una batalla por el control de la misma. Peeta aprovecha la confusión del momento para enviar un mensaje a los rebeldes advirtiéndoles de un ataque, sin embargo, inmediatamente, El Capitolio irrumpe en caos, la cámara cae al suelo, y la escena se desvanece escuchándose los gritos de Peeta. Más aún, se vislumbra el esparcir de su sangre en el suelo, haciéndolos pensar que Peeta está siendo torturado.</p>
            <h3>parte II</h3>
            <p>La advertencia de Peeta le da a los rebeldes 10 minutos de adelanto para poner en marcha el plan de contingencia previsto para salvaguardar los habitantes del Distrito 13 en los búnkeres subterráneos, lo que Boggs más adelante confirmará, significó más vidas salvadas gracias a que la evacuación de la población fue total.</p>
            <p>Durante la primera noche de su estancia en el búnker, Katniss mantiene una conversación con su hermana Prim, acerca de sus estadías en el distrito 13. Al poco tiempo, el intercambio gira inevitablemente hacia el asunto de Peeta y Katniss, cuando la última no puede ocultar que se encuentra preocupada porque la rebeldía del aviso de Peeta pueda significar su muerte. Para su sorpresa, Prim le aclara, de una forma un poco tenebrosa, que Snow jamás matará a Peeta. En cambio, lo mantendrá vivo cuanto pueda, porque sabe que el muchacho es la única arma que posee contra ella, y hará lo que pueda con él para destrozarla. Katniss se encuentra muy perturbada por esta afirmación, y después de un encuentro con Finnick que le confirma lo dicho por Prim, cae en una pequeña depresión.</p>
            <p>El bombardeo del Distrito 13 termina, y con ello, Katniss, Finnick y Gale son llamados para realizar una propo y mostrar a Panem que el distrito 13 aún sigue en pie y ellos con vida. Al salir a la superficie, cuando ella mira por encima de los escombros dejados por el bombardeo, ve que el Presidente Snow ha dejado más rosas. El efecto es devastador. Katniss empieza a llorar cuando el equipo de filmación le dice que pronuncie una línea a la cámara, para demostrar que sigue con vida y todavía batallando. Finnick explica al perplejo equipo de filmación que Katniss sabe que el Capitolio lastimará a Peeta si ella lo hace.</p>
            <p>Katniss es sedada. Al despertar, se topa con Haymitch, quién está a su lado. Haymitch le comunica que han enviando un grupo para rescatar a Peeta, sabiendo que ella no hará más nada hasta saber que el Capitolio no puede herirlo. Impulsada por la necesidad de ayudar, Katniss y Finnick graban una propo que será utilizada como distracción mientras la misión de rescate se pone en marcha en el Capitolio. La propo tiene un gran impacto gracias a que Finnick utiliza los “Secretos” con los que le pagaban sus amantes para atraer grandemente la atención, en especial cuando revela la historia oscura de ascenso al poder del Presidente Snow, y su relación con las rosas. La misión es declarada un éxito, logrando salvar no sólo a Peeta, sino a Annie y a Johanna también. Katniss y Peeta se reecuentran, pero la reunión toma una orientación inesperada. Al mirar a Katniss, Peeta se encamina hacia ella y rodea con sus manos el cuello de la muchacha.</p>
            <p>Antes de darse cuenta, Peeta ya se halla tratando de estrangularla hasta la muerte.</p>
            <p>Katniss despierta en el hospital. Al reunirse Plutarch, Haymitch y Beetee con Prim, a su lado en la cama del hospital, se entera que el Capitolio ha usado una técnica poco común conocida como "Secuestro". El "Secuestro" fue hecho dándole a Peeta dosis de veneno de Rastrevíspula, mientras se le mostraba vídeos de Katniss y diciéndole que ella destruyó su familia y amigos, por lo tanto, engañándolo para que la odiara.</p>
            <p>Ante esto, el dolor de Katniss no le permite permanecer en el Distrito 13. Aunque pide ir al Capitolio, se le indica que esto no tendrá lugar hasta que el Distrito 2 sea tomado. Katniss pide entonces ser despachada al Distrito 2 para presenciar la toma de "El Hueso", el último bastión de resistencia del distrito. Luego de ello, Katniss es regresada al Distrito 13, donde comienza a entrenar como soldado para la invasión al Capitolio. Al terminar su entrenamiento es asignada al Escuadrón 451 bajo el comando de Boggs, sin embargo, ese mismo escuadrón es señalado para la grabación de propos concernientes a la guerra, y por lo tanto no estarán en combate real.</p>
            <p>Una vez enviados al Capitolio, en la cuarta mañana, un soldado del escuadrón, de nombre Leeg 2, activa un dispositivo (vaina) que no estaba bien señalizado ocasionando una lluvia de dardos de metal que le causa la muerte. Un reemplazo es enviado inmediatamente, y llega en la noche del día siguiente.</p>
            <p>Todos están conmocionados cuando reconocen al nuevo soldado. Nadie puede creer que Peeta está ahí.</p>
            <h3>parte III</h3>
            <p>Después de la llegada de Peeta, Boggs hace una llamada a Coin acerca de su envío al escuadrón. Cuando regresa, dice que él cree que Coin despachó a Peeta personalmente para asesinar a Katniss ya que después de la guerra, un nuevo líder será elegido y Katniss, teniendo mucha influencia como el Sinsajo, será una amenaza si su voto no va para Coin. Para detener a Katniss, Coin trasladó a Peeta al Escuadrón, esperando que él la matara. Después de una llamada de Haymitch, Katniss resuelve intentar ayudar a Peeta a rememorar sus recuerdos reales. El Escuadrón crea un juego, "Real o no real", para ayudarlo a separar sus recuerdos secuestrados de los verdaderos. Durante esto, Peeta revela que cuando estaba secuestrado en el Capitolio, ellos lo forzaron a ver la ejecución de dos Avoxes, Darius y Lavinia, con el pretexto de tratar de obtener información sobre la rebelión.</p>
            <p>Durante la filmación de una propo, Boggs pisa una vaina mal etiquetada que vuela sus piernas. Al mismo tiempo, otra vaina es activada, creando una ola negra que avanza hacía el Escuadrón. Mientras trataban de mover a Boggs a un apartamento para escapar de la ola, Peeta tiene un episodio y casi mata a Katniss con una pistola. Cuando un miembro del Escuadrón, Mitchell, trata de detenerlo, Peeta accidentalmente lo mata lanzándolo fuera de él, causando que cayera en otra vaina mal etiquetada que encierra a Mitchell en una red de alambre de púas. Dentro del apartamento, Boggs transfiere el Holo a Katniss y muere después de decirle cuatro órdenes: "No confíes en ellos, no vuelvas. Mata a Peeta. Haz lo que has venido a hacer". Katniss le dice al equipo que ella estaba en una misión secreta para matar al Presidente Snow con ordenes de Coin. Ella admite que sólo Boggs lo sabía, Cressida respalda la historia de Katniss, diciendo que Plutarch quería que el asesinato de Snow fuera televisado, pensando que eso terminaría la guerra.</p>
            <p>Ellos caminan hacía un apartamento abandonado y encuentran sofás esparcidos por la habitación. Todos se sientan, con Jackson todavía apuntando su arma hacía Peeta. La televisión pronto se enciende para informar a Panem que Katniss, Gale, Finnick, Boggs, Peeta y Cressida están muertos. Peeta sugiere que lo maten pero Katniss no lo permite, diciendo que él es muy importante para la misión como para perderlo. Después de conseguir comida , Snow aparece en la televisión para hablar acerca de cómo Katniss era sólo una niña, no una líder y que el Capitolio ahora ganará la guerra. El Distrito 13 toma la transmisión y la Presidenta Coin dice que ella cree en lo que el Sinsajo representaba y que los rebeldes encontrarán la fuerza que necesitan para librarse de sus opresores.</p>
            <p>El lado positivo de que todos piensen que están muertos es que tienen una ventaja. Empiezan a buscar una manera para salir, ya que las calles no son una posibilidad y los techos son igual de malos. El Equipo se dirige hacía las alcantarillas con la ayuda del Avox Pollux y empiezan a avanzar por el subterráneo. Después de dormir, son atacados por mutos de lagartos. Después de correr por un momento y la muerte de varios miembros del equipo, incluyendo a Finnick, el equipo escapa.</p>
            <p>El equipo logra permanecer en el sótano de la tienda de Tigris, donde se quedan por un par de días y observan a los rebeldes avanzar. Mientras esperaban, los ciudadanos del Capitolio son enviados a las afueras de la ciudad. Con la ayuda de Tigris, Katniss, Peeta y Gale se mezclan con la multitud.</p>
            <p>Mientras huyen lejos en el Capitolio con la intención de encontrar y matar al Presidente Snow, Katniss se encuentra sola presionando para entrar en la mansión de Snow, que había sido supuestamente abierta para albergar a los niños del Capitolio (pero en realidad estaba destinado para proveer escudos humanos a Snow). Después, las bombas colocadas en paquetes de suministros mata a mucho de estos niños, médicos rebeldes, y la hermana de Katniss, Prim, mientras Katniss queda severamente quemada.</p>
            <p>El Presidente Snow es juzgado y declarado culpable, pero él le dice a Katniss que el asalto final que mató a Primrose Everdeen fue ordenado por la Presidenta Coin, no por el Capitolio. Katniss se da cuenta que si ésta es la verdad, el bombardeo pudo haber sido resultado de un plan originalmente desarrollado por su amigo Gale, sin embargo, Gale negó su participación.</p>
            <p>Katniss recuerda una conversación con Snow en donde se prometieron no mentirse entre ellos. Cuando se supone que debe ejecutar a Snow, se da cuenta que él decía la verdad y mata a Coin en su lugar. Se produce un alboroto y Snow es encontrado misteriosamente muerto, posiblemente ahogándose con su propia sangre o pisoteado por la multitud. Katniss es absuelta por su aparente locura. </p>
            <p>Luego regresa junto a Haymitch a el Distrito 12, y meses más tarde, recuperado enormemente de su lavado de cerebro, Peeta. Finalmente, Katniss se da cuenta que enamorarse de Peeta era inevitable, ya que él siempre había representado la promesa de un mejor futuro, en lugar de la destrucción que ella asocia ahora con Gale. </p>
            <p>Ella dice que no necesitaba el fuego de Gale, ya que ella lo tenía en sí misma; necesitaba a Peeta, que simboliza la esperanza que ella necesitaba para sobrevivir ("Lo que necesito es el diente de león en primavera, el brillante color amarillo que significa renacimiento y no destrucción. La promesa de que la vida puede continuar por dolorosas que sean nuestras pérdidas, que puede volver a ser buena"). Junto con Haymitch, ellos crean un libro lleno con historias de los anteriores tributos y otros que murieron en la guerra para que así no sean olvidados.</p>
            <h3>Epilogo</h3>
            <p>Katniss habla como un adulto, más de quince años después. Ella y Peeta "crecieron de nuevo juntos" y aunque no se indica si se casaron tienen dos hijos juntos, un niño y una niña. Los Juegos del Hambre acabaron, pero ella teme el día que el mundo inocente de sus hijos sea destrozado por conocer la participación de sus padres en ambos Juegos y en la guerra. Cuando se siente molesta, Katniss hace una lista mental de todas las cosas buenas que ha sido testigo.</p>
            <p>"Es como un juego, repetitivo, incluso algo tedioso después de más de veinte años. Aun así, sé que hay juegos mucho peores".</p>
            <img src="../Media/balada3.jpg" alt="Balada de pajaros cantores y serpientes" class="imagen">
        </div>
        <div class="Personajes">
            <h2>Personajes</h2>
            Katniss Everdeen - Simboliza el Sinsajo para los rebeldes. Ella se abrió paso en el Capitolio y puso fin a la rebelión. Asesinó a la Presidenta Coin. Vive en el Distrito 12. Se convirtió en el símbolo de la Rebelión en contra del Capitolio. Regresa al Distrito 12 después de la guerra, ella y Peeta volvieron a estar juntos. No está claro si está casada con Peeta pero se sabe que lo ama en un juego final de "Real o no" al final de la Parte III del tercer libro. En el epílogo, se muestra que Peeta y Katniss están en la pradera del Distrito 12 los dos juntos, más sus dos hijos, un niño y una niña.
Peeta Mellark - Estaba en la arena con Katniss, pero fue capturado por el Capitolio. Peeta ha amado a Katniss desde que eran niños pequeños. Fue secuestrado por el Capitolio después de los 75º Juegos del Hambre, y sus recuerdos fueron distorsionados para hacer que odiara a Katniss. Debido a esto, intentó matar a Katniss, aunque sin resultado alguno. Finalmente se cura y regresa al Distrito 12, meses después que su amada. Se casan, crecen juntos y tienen dos hijos, una niña y un niño.
Primrose Everdeen - Es la hermana pequeña de Katniss. Primrose ayuda a su hermana a mantener la cordura cuando Peeta no está. Prim trabaja como sanadora en el Distrito 13, y muere durante un bombardeo que, se supone, fue ocasionado por parte de los soldados de Coin, cuando un aerodeslizador con bombas paracaídas lanza las mismas a un grupo de niños del Capitolio, lugar donde Prim trabajaba como médico durante la explosión.
Gale Hawthorne - Es el mejor amigo de Katniss y su compañero de caza. Está enamorado de Katniss, pero no terminan juntos, ya que ella lo culpa por la muerte de Prim. Gale termina siendo un oficial del gobierno en el Distrito 2.
Haymitch Abernathy - Antiguo vencedor del Distrito 12, que recurrió al alcohol para olvidar su pasado en los juegos. Solía ser un mentor para Los Juegos del Hambre. Ayudó en la rebelión y luego regresó al Distrito 12, donde sigue siendo alcohólico. Fue el vencedor de los 50º Juegos del Hambre.
Effie Trinket - Es la escolta de Peeta y Katniss en los 74º y 75º Juegos del Hambre. Es una residente del Capitolio, por lo que viste con ropas extrañas y tiene el distintivo acento del Capitolio. Es arrestada al final de los 75º Juegos del Hambre y soltada cuando los rebeldes ganan la guerra contra el Capitolio. Ella vió como Katniss mató a la Presidenta Coin. Luego de esto regresa a su hogar en el Capitolio.
Plutarch Heavensbee - Fue el Jefe de los Vigilantes en los 75º Juegos del Hambre, pero secretamente trabajaba con los rebeldes para derrocar al Capitolio.
Finnick Odair - Vencedor de los 65º Juegos del Hambre. El presidente Snow lo forzó a vender su cuerpo a la gente rica del Capitolio después de convertirse en el vencedor de sus Juegos del Hambre, amenazándolo con matar a la gente que amaba si no lo hacía. Originario del Distrito 4. Ayudó en la rebelión contra el Capitolio. Él y Katniss se ayudaron entre ellos a mantener la cordura cuando Peeta y Annie estaban secuestrados. Se casa con Annie Cresta después de que ella es rescatada del Capitolio, pero es asesinado por mutos en forma de lagarto durante la misión de asesinar al Presidente Snow. Él y Annie tienen un hijo, el cual nunca conoció a su padre.
Annie Cresta - Vencedora de los 70º Juegos del Hambre, perdió la cordura cuando vio a su compañero de Distrito ser decapitado. Es arrestada por el Capitolio después del Vasallaje de los Veinticinco. Ella es el amor de Finnick Odair y más tarde se convierte en su esposa. Enviuda, cuando él es asesinado por mutos durante la misión del asesinato al presidente Snow, y más tarde da a luz a su hijo.
Johanna Mason - Es la tributo del Distrito 7. Participó en el 71º Juegos del Hambre y también participó en el tercer Vasallaje de los Veinticinco. Después de la destrucción de la arena de los 75º Juegos del Hambre es secuestrada y torturada por el Capitolio. Es rescatada por los rebeldes y empieza a entrenar como soldado junto con Katniss para luchar en la rebelión, aunque su trauma al agua debido a las torturas sufridas en el Capitolio le impide convertirse en uno.
Presidente Coriolanus Snow - El Presidente cruel de Panem, muere asfixiado por su propia sangre o siendo pisoteado. Katniss señaló que a nadie le importó. Olía a rosas y sangre ya que envenenaba a la personas para llegar al poder. Él también bebía del veneno con el que envenenaba a la gente para no levantar sospechas. Tomaba un antídoto después, pero igualmente se le formaban heridas en su boca, que desprendían olor a sangre por lo que usaba perfume de rosas para taparlo.
Presidenta Alma Coin - Es la presidenta del Distrito 13. Autorizó el bombardeo de los niños del Capitolio, donde murió Prim. Katniss la mata por venganza durante la ejecución de Snow.
Boggs - Guardaespaldas de Katniss y capitán del ejército. Es asesinado en la batalla, pero no antes de transferir el mando y el Holo a Katniss para que pudiera continuar con su misión de matar al presidente Snow. Su último consejo es matar a Peeta, no confiar en nadie, y hacer lo que ella vino a hacer en el Capitolio, matar a Snow.
Comandante Paylor - Es la líder de los rebeldes del Distrito 8, la cuál más tarde se convertiría en la presidenta de Panem, después de que Katniss asesinara a la Presidenta Coin en la ejecución de Snow.
        </div>
    </section>
</template>
